module.exports = {
	SPELLCHECK_DEBUG: process.env.SPELLCHECK_DEBUG,
	SPELLCHECK_FLAGS: process.env.SPELLCHECK_FLAGS,
	SPELLCHECK_TIMER: process.env.SPELLCHECK_TIMER,
	SPELLCHECK_URL: process.env.SPELLCHECK_URL,
};
